params_infer:
  R:
    index: 0 
    scalers:
      type: "uniform"
      params:
        min: 0.0
        max: 255.0
  G:
    index: 1 
    scalers:
      type: "uniform"
      params:
        min: 0.0
        max: 255.0
  B:
    index: 2 
    scalers:
      type: "uniform"
      params:
        min: 0.0
        max: 255.0
  alpha:
    index: 6 
    scalers:
      type:
      params:



backbone:
  name: "CNN2DBackbone"
  params_sim: 5
  params:
    num_layers: 6
    input_channels: 3
    input_size: 500
    output_size: 16 
    num_filters: 16 
    kernel_size: 3



real_data:
  name: "LightTunnel"
  params:
    exp_name: "uniform_ap_1.8_iso_500.0_ss_0.005"

  train:
    num_samples: 1000
    idx_offset: 0

  val:
    num_samples: 200
    idx_offset: 1000

  calib_train:
    num_samples: 50
    idx_offset: 1200

  calib_test:
    num_samples: 1000
    idx_offset: 2200

sim_data:
  name: "LightTunnelModelF3"
  params:  {}
    
  train:
    num_samples: 1000
    seed_offset: 0

  val:
    num_samples: 200
    seed_offset: 1000
  
  test:
    num_samples: 1000
    seed_offset: 1200

  



training:
  num_workers: 4
  num_folds: 5
  epochs: 100
  lr_npe: 0.0001
  lr_nse_ft: 0.0001 #0.00005
  lr_nf_align: 0.0001 #0.0001
  tau_a: 1e10
  tau_b: 1e10
  gamma: 0.5
  posterior_train_sample: 100
  posterior_test_sample: 1000
  npe_ckpt: "bzhy1lhe"
  nse_ckpt: ""  
  nf_align_ckpt: "" 
  wassOT_ft_ckpt: "" 
  nf_wassOT_align_ckpt: "" 
  early_stopping: [false, false, false]
  patience: [10, 5, 5]

sweep_hyperparams:
  lr_nse_ft_end_to_end: [0.0001] #[0.0001, 0.001]
  batch_size: [64] #[32, 64, 128]